//go:build !windows

package install

import (
	"fmt"
	"os"
	"path/filepath"
)

const secondClientHomeUnix = "/tmp/jk2-client2"

// writeLaunchers writes the jk2coop-host and jk2coop-join bash launchers and
// records them in the manifest.
func writeLaunchers(p Platform, man *Manifest, engineBin, gamecode string) error {
	host := fmt.Sprintf(`#!/usr/bin/env bash
# jk2coop-host [map] — start a co-op game others can join. Generated by jk2coop install.
exec %q \
    +set fs_basepath %q \
    +set net_enabled 1 +set net_port %d \
    +map "${1:-%s}"
`, engineBin, p.DataDir, defaultPort, defaultMap)

	if err := writeScript(p.HostLauncher(), host); err != nil {
		return err
	}
	if err := man.Add(p.HostLauncher()); err != nil {
		return err
	}

	secondHome := envOr("TMPDIR", "/tmp")
	secondHome = filepath.Join(secondHome, "jk2-client2")
	if p.OS != "darwin" {
		secondHome = secondClientHomeUnix
	}

	join := fmt.Sprintf(`#!/usr/bin/env bash
# jk2coop-join <host[:port]> [--second] — join a co-op game. Generated by jk2coop install.
set -euo pipefail
if [[ $# -lt 1 || "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    echo "usage: jk2coop-join <host[:port]> [--second]" >&2
    exit 1
fi
host="$1"; shift || true
case "$host" in *:*) : ;; *) host="$host:%d" ;; esac

args=( +set fs_basepath %q +set net_enabled 1 )
if [[ "${1:-}" == "--second" ]]; then
    # A second client ON THE SAME MACHINE needs its own clean fs_homepath, and
    # its own copy of the gamecode there (the SP loader searches homepath first).
    rm -rf %q
    mkdir -p %q/base
    ln -sfn %q %q/base/%s
    args+=( +set fs_homepath %q )
fi
exec %q "${args[@]}" +connect "$host"
`,
		defaultPort, p.DataDir,
		secondHome, secondHome,
		gamecode, secondHome, p.GamecodeName,
		secondHome, engineBin)

	if err := writeScript(p.JoinLauncher(), join); err != nil {
		return err
	}
	return man.Add(p.JoinLauncher())
}

func writeScript(path, content string) error {
	return os.WriteFile(path, []byte(content), 0o755)
}
