//go:build windows

package install

import (
	"fmt"
	"os"
	"path/filepath"
)

// writeLaunchers writes the jk2coop-host and jk2coop-join .cmd launchers and
// records them in the manifest.
func writeLaunchers(p Platform, man *Manifest, engineBin, gamecode string) error {
	host := fmt.Sprintf("@echo off\r\n"+
		"rem jk2coop-host [map] - start a co-op game others can join. Generated by jk2coop install.\r\n"+
		"set MAP=%%1\r\n"+
		"if \"%%MAP%%\"==\"\" set MAP=%s\r\n"+
		"\"%s\" +set fs_basepath \"%s\" +set net_enabled 1 +set net_port %d +map \"%%MAP%%\"\r\n",
		defaultMap, engineBin, p.DataDir, defaultPort)

	if err := os.WriteFile(p.HostLauncher(), []byte(host), 0o755); err != nil {
		return err
	}
	if err := man.Add(p.HostLauncher()); err != nil {
		return err
	}

	secondHome := filepath.Join(envOr("TEMP", `C:\Temp`), "jk2-client2")
	join := fmt.Sprintf("@echo off\r\n"+
		"rem jk2coop-join <host[:port]> [--second] - join a co-op game. Generated by jk2coop install.\r\n"+
		"setlocal enabledelayedexpansion\r\n"+
		"if \"%%1\"==\"\" ( echo usage: jk2coop-join ^<host[:port]^> [--second] 1>&2 & exit /b 1 )\r\n"+
		"set HOST=%%1\r\n"+
		"echo %%HOST%% | findstr /c:\":\" >nul || set HOST=%%HOST%%:%d\r\n"+
		"if /i \"%%2\"==\"--second\" (\r\n"+
		"  rmdir /s /q \"%s\" 2>nul\r\n"+
		"  mkdir \"%s\\base\" 2>nul\r\n"+
		"  copy /y \"%s\" \"%s\\base\\%s\" >nul\r\n"+
		"  \"%s\" +set fs_basepath \"%s\" +set net_enabled 1 +set fs_homepath \"%s\" +connect \"%%HOST%%\"\r\n"+
		") else (\r\n"+
		"  \"%s\" +set fs_basepath \"%s\" +set net_enabled 1 +connect \"%%HOST%%\"\r\n"+
		")\r\n",
		defaultPort,
		secondHome, secondHome,
		gamecode, secondHome, p.GamecodeName,
		engineBin, p.DataDir, secondHome,
		engineBin, p.DataDir)

	if err := os.WriteFile(p.JoinLauncher(), []byte(join), 0o755); err != nil {
		return err
	}
	return man.Add(p.JoinLauncher())
}
