// Package embed carries the OpenJK source, co-op patches, and co-op UI assets
// baked into the jk2coop binary, so a released binary can build and install the
// game with no git checkout and no network access.
//
// Contents (regenerated by gen.go via `go generate ./internal/embed`):
//
//   - openjk-src.tar.gz — the pruned OpenJK source tree at the pinned commit
//     (only what the JK2-SP build compiles, plus codemp so the full patch set
//     applies). ExtractSource writes it to a work dir.
//   - pin.txt — the submodule commit the archive was built from. Pin() returns
//     it; the work-dir manifest records it so a stale extraction is re-done.
//   - patches/*.patch — the co-op patch set, applied in pure Go (no git).
//   - coop-ui/ — the co-op UI overlay assets used to build zz-coop-ui.pk3.
//
//go:generate go run gen.go
package embed

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"embed"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

//go:embed openjk-src.tar.gz
var srcArchive []byte

//go:embed pin.txt
var pinText string

//go:embed patches/*.patch
var patchesFS embed.FS

//go:embed all:coop-ui
var coopUIFS embed.FS

// Pin returns the OpenJK submodule commit the embedded source was built from.
func Pin() string {
	return strings.TrimSpace(pinText)
}

// ExtractSource writes the embedded OpenJK source tree into dest, creating it if
// needed. dest is populated with the tree root directly (dest/CMakeLists.txt,
// dest/code/…). It does NOT clean dest first — callers that need a pristine tree
// should remove dest beforehand (see workdir.ExtractPristine).
func ExtractSource(dest string) error {
	gz, err := gzip.NewReader(bytes.NewReader(srcArchive))
	if err != nil {
		return fmt.Errorf("opening embedded source archive: %w", err)
	}
	defer func() { _ = gz.Close() }()

	tr := tar.NewReader(gz)
	for {
		hdr, err := tr.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			return fmt.Errorf("reading source archive: %w", err)
		}
		// Guard against path traversal from a malformed archive.
		clean := filepath.Clean(hdr.Name)
		if clean == ".." || strings.HasPrefix(clean, ".."+string(filepath.Separator)) {
			return fmt.Errorf("archive entry escapes dest: %q", hdr.Name)
		}
		target := filepath.Join(dest, filepath.FromSlash(clean))
		switch hdr.Typeflag {
		case tar.TypeDir:
			if err := os.MkdirAll(target, 0o755); err != nil {
				return err
			}
		case tar.TypeReg:
			if err := writeEntry(target, tr, hdr.Size); err != nil {
				return err
			}
		}
	}
	return nil
}

// writeEntry writes one regular tar entry to target. It copies at most size
// bytes (the header's declared length) so a malformed archive cannot stream an
// unbounded amount into the file — the archive is our own trusted embed, but the
// bound keeps the extraction honest regardless.
func writeEntry(target string, tr *tar.Reader, size int64) error {
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return err
	}
	f, err := os.OpenFile(target, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0o644)
	if err != nil {
		return err
	}
	if _, err := io.Copy(f, io.LimitReader(tr, size)); err != nil {
		_ = f.Close()
		return err
	}
	return f.Close()
}

// Patch is one embedded patch: its filename (basename) and bytes.
type Patch struct {
	Name string
	Data []byte
}

// Patches returns the co-op patch set sorted in apply order (their numeric
// prefix makes lexical order the intended order).
func Patches() ([]Patch, error) {
	ents, err := patchesFS.ReadDir("patches")
	if err != nil {
		return nil, err
	}
	names := make([]string, 0, len(ents))
	for _, e := range ents {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".patch") {
			names = append(names, e.Name())
		}
	}
	sort.Strings(names)
	out := make([]Patch, 0, len(names))
	for _, n := range names {
		b, err := patchesFS.ReadFile("patches/" + n)
		if err != nil {
			return nil, err
		}
		out = append(out, Patch{Name: n, Data: b})
	}
	return out, nil
}

// ExtractCoopUI writes the embedded co-op UI assets (the ui/ subtree and the
// prebuilt zz-coop-ui.pk3) into dest/, mirroring the layout of assets/coop-ui.
func ExtractCoopUI(dest string) error {
	return fs.WalkDir(coopUIFS, "coop-ui", func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel("coop-ui", p)
		if err != nil {
			return err
		}
		target := filepath.Join(dest, rel)
		if d.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		b, err := coopUIFS.ReadFile(p)
		if err != nil {
			return err
		}
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return err
		}
		return os.WriteFile(target, b, 0o644)
	})
}
